### ISSUE TITLE
Bind Error?

### ISSUE THREAD

**Issue by farhan94** [jacobrask/node-upnp-device#19] opened 2017-03-08 03:10 UTC
Error: bind EADDRNOTAVAIL 239.255.255.250:1910
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at dgram.js:221:18
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Any known ways to solve this one?

**Comment by eelcocramer** [comment] 2017-03-08 15:32
Can you post your code or provide us with a sample that can reproduce your issue? What version of node are you using on what platform?

What seems to be the root problem is that you cannot bind to that IP address.

**Comment by farhan94** [comment] 2017-03-08 16:37
I am using Node version 6.9.4

I am trying to run the code in the Examples folder of this repo. This is my code in my index.js file, so I feel like it should be working. I recognize that it isn't able to bind the IP address at the point in the library code where it's trying to create an SSDP server (I THINK), but no matter what IP I put into the original source code (for starting the SSDP server) it says its not available or it's in use.
index.js:
`var express = require('express');

var router = express.Router();

 var upnp = require('upnp-device');
 var myDevice = require('./MyDevice');
 var device = upnp.createMyDevice(myDevice, 'My Device');

 device.on('ready', function() {
     device.Announce();
 });

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'Express' });
});


module.exports = router;`

**Comment by eelcocramer** [comment] 2017-03-20 16:00
I was able to reproduce this with node v4 and v6. Node v0.10 did not have the problem yet. I nailed it down to a call to bind. I made a fix and this seems to work on node v4 and v6. The fix is included in a new version that was published to npm just now (v0.1.9).

**Closed by eelcocramer** 2017-03-20 16:00 UTC
